title: Sz-Je Wang # your name (or website title) here
logo: "images/Szjewangpicture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://www.linkedin.com/in/sz-je-wang-b2916123a/">LinkedIn</a> 
  <br>
  <a href="pdf/Resume.pdf" class="btn btn--info">Resume</a>   
  <br>
  <a href="https://www.GitHub.com/stevenwang1213">GitHub</a>  
  <br>
  
Table of contents:
1. [About Me](#me)
2. [Portfolio](#portfolio)
    - [Natural language processing on Fed announcements](#fed)
    - [Natural language processing 10-Ks to identify risks](#10k)
    - [Regression Practice](#reg)
    - [The collapse of Silicon Valley Bank and Signature bank](#svb)
3. [Job Description and Career Objective](#career)
4. [Hobbies](#hobbies)

theme: jekyll-theme-minimal
